version: "3.8"

volumes:

  mongodb_data:
    name: ${VW_VOLUME_MONGODB_ID}

  elastic_data:
    name: ${VW_VOLUME_ELASTIC_ID}

services:

  # MongoDB database service
  mongodb:
    image: mvertes/alpine-mongo:4.0.6-1
    volumes:
      - mongodb_data:/data/db
    restart: always

  # Elasticsearch search server service
  elastic:
    image: blacktop/elasticsearch:7.9.2
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: always

  # the actual VedaWeb application, built based on Dockerfile
  app:
    build: .
    volumes:
      - ./resources:/vedaweb/resources
    restart: always
    ports:
      - "127.0.0.1:${VW_WEBAPP_HOST_PORT}:8080" # the application will be served via the host port set in .env
    depends_on:
      - mongodb
      - elastic